In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [2]:
data = pd.read_csv('pp5i_train.gr.csv')                 #read train data
df_test= pd.read_csv('pp5i_test.gr.csv')                # read test data
df_test

SNO  101  102  103  104  105  106  107  108  109  ...  114  115  \
0       A28102_at   58   52   13   46   48   31   16   23   47  ...   11   19   
1     AB000114_at   36   34   32   30   22   57   17   19   29  ...   17   57   
2     AB000115_at   10  255    0   14   17   -6   15   17   33  ...   18   -2   
3     AB000220_at   64   19  133   62  110   77   22   33  132  ...   84   34   
4     AB000409_at   17  220  186  232  169  251  210  142  131  ...  209  166   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
7065    X83863_at  288  161  400  206  171  257  216  155  284  ...  164  494   
7066    Z17240_at   74   33   36   44   42   43   23   51   35  ...   39  104   
7067  L49218_f_at    5    6  -24   13    8    9    7    8    6  ...    4    7   
7068  M71243_f_at   61   22   55   51   16   82   48   34   24  ...   37   36   
7069  Z78285_f_at    0   -1    2    0   -2    9  -13   -2    1  ...    0    6   

      116  117  118  119  120  121  122  123  
0      18   70   50   29   47   44   56  119  
1      25   50   36   26   28   34   45   53  
2      -7  148  145   13  361   16    7   34  
3      30   69  108   75  184   57   26   83  
4     260  241  165  111  170  147  246  204  
...   ...  ...  ...  ...  ...  ...  ...  ...  
7065  197  277  147  113  136  157  176  198  
7066   40   31   44   39   55   48   62   37  
7067   17  -24   14  -13   10   11    3   -7  
7068   62   27   24   -1   41   34   55   60  
7069   -3  -46   -2  -24   -1    0   -8   -8  

[7070 rows x 24 columns]

In [3]:
v_test=df_test.transpose()                #transpose of test data
v_test                                    


0            1            2            3            4     \
SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at   
101         58           36           10           64           17   
102         52           34          255           19          220   
103         13           32            0          133          186   
104         46           30           14           62          232   
105         48           22           17          110          169   
106         31           57           -6           77          251   
107         16           17           15           22          210   
108         23           19           17           33          142   
109         47           29           33          132          131   
110         42           14           22           18          113   
111         46           20           41           30          170   
112         28           32           12           32          252   
113         25           19           13          465          135   
114         11           17           18           84          209   
115         19           57           -2           34          166   
116         18           25           -7           30          260   
117         70           50          148           69          241   
118         50           36          145          108          165   
119         29           26           13           75          111   
120         47           28          361          184          170   
121         44           34           16           57          147   
122         56           45            7           26          246   
123        119           53           34           83          204   

            5            6            7            8            9     ...  \
SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...   
101            8          -36          222          119          254  ...   
102           28            3          209           93          143  ...   
103           -6          -58          174           66          204  ...   
104           -1          -29          188           62          162  ...   
105           21           -2          158           42           59  ...   
106           -1          -87          210          179          339  ...   
107           19            4          174          124          183  ...   
108           27          -14          144           36          106  ...   
109           17           -5          167           44          100  ...   
110            8            0          140           36          104  ...   
111           11           21          175           41          111  ...   
112           30          -77          206           41          279  ...   
113          200           21          159           37           90  ...   
114           14          -39          244           85          212  ...   
115            0          -46          182           52          184  ...   
116            4          -31          157          185          247  ...   
117           13           26          238          136          135  ...   
118           15           18          169           35           84  ...   
119           69           -7          181           45          109  ...   
120            5           15          188           76          127  ...   
121            8            5          236           71          126  ...   
122            4          -19          240           77          206  ...   
123            3          -23          157          106          225  ...   

          7060       7061       7062       7063       7064       7065  \
SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at   
101         25        216          0         10         -2        288   
102         25        236          0         20          1        161   
103          7        138         -5     

In [4]:
v_test.columns=df_test['SNO']          

In [5]:
v_test=v_test.drop('SNO')             #remove row of 'SNO'

In [6]:
v_test.describe()                      

SNO     A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
count          23           23           23           23           23   
unique         21           17           21           22           22   
top            46           36           13           30          170   
freq            2            2            2            2            2   

SNO     AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...  \
count            23           23           23           23           23  ...   
unique           19           22           20           21           23  ...   
top               8           21          174           36          254  ...   
freq              3            2            2            2            1  ...   

SNO     U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at  \
count          23         23         23         23         23         23   
unique         15         21          9         22         14         23   
top            25        138          0         14          1        288   
freq            4          2          9          2          4          1   

SNO     Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
count          23           23           23           23  
unique         18           15           19           12  
top            32            6           23           -2  
freq            2            3            2            5  

[4 rows x 7070 columns]

In [7]:
v_test = v_test.clip(2,16000)          #clip the data from 2 to 16000

In [8]:
v_test

SNO A28102_at AB000114_at AB000115_at AB000220_at AB000409_at AB000449_at  \
101        58          36          10          64          17           8   
102        52          34         255          19         220          28   
103        13          32           2         133         186           2   
104        46          30          14          62         232           2   
105        48          22          17         110         169          21   
106        31          57           2          77         251           2   
107        16          17          15          22         210          19   
108        23          19          17          33         142          27   
109        47          29          33         132         131          17   
110        42          14          22          18         113           8   
111        46          20          41          30         170          11   
112        28          32          12          32         252          30   
113        25          19          13         465         135         200   
114        11          17          18          84         209          14   
115        19          57           2          34         166           2   
116        18          25           2          30         260           4   
117        70          50         148          69         241          13   
118        50          36         145         108         165          15   
119        29          26          13          75         111          69   
120        47          28         361         184         170           5   
121        44          34          16          57         147           8   
122        56          45           7          26         246           4   
123       119          53          34          83         204           3   

SNO AB000450_at AB000460_at AB000462_at AB000464_at  ... U48730_at U58516_at  \
101           2         222         119         254  ...        25       216   
102           3         209          93         143  ...        25       236   
103           2         174          66         204  ...         7       138   
104           2         188          62         162  ...         8       152   
105           2         158          42          59  ...        27       146   
106           2         210         179         339  ...         5       102   
107           4         174         124         183  ...        12       138   
108           2         144          36         106  ...        47        98   
109           2         167          44         100  ...        24       165   
110           2         140          36         104  ...        25       310   
111          21         175          41         111  ...        31       301   
112           2         206          41         279  ...        28        69   
113          21         159          37          90  ...        19       124   
114           2         244          85         212  ...        10        80   
115           2         182          52         184  ...        12        74   
116           2         157         185         247  ...         5        95   
117          26         238         136         135  ...        26       326   
118          18         169          35          84  ...        28       143   
119           2         181          45         109  ...        25       225   
120          15         188          76         127  ...        28       197   
121           5         236          71         126  ...        20       201   
122           2         240          77         206  ...        15       135   
123           2         157         106         225  ...        10       236   

SNO U73738_at X06956_at X16699_at X83863_at Z17240_at L49218_f_at M71243_f_at  \
101         2        10         2       288        74           5          61   
102         2        20         2       161        33           6   

In [9]:
data

SNO    1    2    3    4    5    6    7    8    9  ...   60   61  \
0       A28102_at   30   46   31   31   26   28   35   29   21  ...   35   49   
1     AB000114_at   22   31   19   16   26   24   29   20   23  ...   38   30   
2     AB000115_at   29   70   12   11   14   13   14   18   10  ...   20  205   
3     AB000220_at   76  208  244   39   85   23  634  159   50  ...   55  203   
4     AB000409_at  167  211  179  119  161  166  228  267  260  ...  137  180   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
7065    X83863_at  116  123  142  134  153  152  139  213  193  ...  117  203   
7066    Z17240_at   44   43   44   38   42   46   46   52   32  ...   30   37   
7067  L49218_f_at    6    9   10    9    7    7   10    0    5  ...    4    8   
7068  M71243_f_at   30   31   28   21   26   29   32   57   34  ...   27   26   
7069  Z78285_f_at    0   -1   -2    0   -2   -2    0   -2   -3  ...    0   -1   

       62   63   64   65   66   67   68   69  
0      31   51   71   68   77   56   41   38  
1      22   24   19   21   22   25   21   17  
2      16   61   62   35   30   65   32   25  
3     152   53   28   30   31   31   27   16  
4     107  147  170  131  132  158  164  172  
...   ...  ...  ...  ...  ...  ...  ...  ...  
7065  136  118  234  297  267  290  255  397  
7066   39   14   47   39   42   36   44   38  
7067   10    1    1    1    6    6    1    7  
7068   22   11   27   27   30   21   33   24  
7069    0   -2   -1   -1   -1    0   -1    3  

[7070 rows x 70 columns]

In [10]:
data.columns

Index(['SNO', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69'],
      dtype='object')

In [11]:
new_data = data.T[:]

In [12]:
new_data

0            1            2            3            4     \
SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at   
1           30           22           29           76          167   
2           46           31           70          208          211   
3           31           19           12          244          179   
4           31           16           11           39          119   
..         ...          ...          ...          ...          ...   
65          68           21           35           30          131   
66          77           22           30           31          132   
67          56           25           65           31          158   
68          41           21           32           27          164   
69          38           17           25           16          172   

            5            6            7            8            9     ...  \
SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...   
1             32            3          165           47          101  ...   
2             15            2          184           36          130  ...   
3            229            5          219           41          131  ...   
4             19            5          156           26           86  ...   
..           ...          ...          ...          ...          ...  ...   
65             8           22          140           37           81  ...   
66             6           -1          150           43          128  ...   
67             6           27          173           54          108  ...   
68             8           13          165           74          121  ...   
69            10            4          145           48          118  ...   

          7060       7061       7062       7063       7064       7065  \
SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at   
1           27        161          0         34          2        116   
2           27        265          0         98          2        123   
3           24        126          0         21          0        142   
4           27        163         -1         16         -1        134   
..         ...        ...        ...        ...        ...        ...   
65          18        364         -1         34          0        297   
66          26        251         -1         45          1        267   
67          17        315          1         27          1        290   
68          21        248          3         46          1        255   
69          16        285          2         61         -4        397   

          7066         7067         7068         7069  
SNO  Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
1           44            6           30            0  
2           43            9           31           -1  
3           44           10           28           -2  
4           38            9           21            0  
..         ...          ...          ...          ...  
65          39            1           27           -1  
66          42            6           30           -1  
67          36            6           21            0  
68          44            1           33           -1  
69          38            7           24            3  

[70 rows x 7070 columns]

In [13]:
data['SNO'][0]

'A28102_at'

In [14]:
new_data.columns = data['SNO']        

In [15]:
df = new_data.drop('SNO')                    #remove row of 'SNO'

In [16]:
df

SNO A28102_at AB000114_at AB000115_at AB000220_at AB000409_at AB000449_at  \
1          30          22          29          76         167          32   
2          46          31          70         208         211          15   
3          31          19          12         244         179         229   
4          31          16          11          39         119          19   
5          26          26          14          85         161          34   
..        ...         ...         ...         ...         ...         ...   
65         68          21          35          30         131           8   
66         77          22          30          31         132           6   
67         56          25          65          31         158           6   
68         41          21          32          27         164           8   
69         38          17          25          16         172          10   

SNO AB000450_at AB000460_at AB000462_at AB000464_at  ... U48730_at U58516_at  \
1             3         165          47         101  ...        27       161   
2             2         184          36         130  ...        27       265   
3             5         219          41         131  ...        24       126   
4             5         156          26          86  ...        27       163   
5            -9         206          34         140  ...        41       138   
..          ...         ...         ...         ...  ...       ...       ...   
65           22         140          37          81  ...        18       364   
66           -1         150          43         128  ...        26       251   
67           27         173          54         108  ...        17       315   
68           13         165          74         121  ...        21       248   
69            4         145          48         118  ...        16       285   

SNO U73738_at X06956_at X16699_at X83863_at Z17240_at L49218_f_at M71243_f_at  \
1           0        34         2       116        44           6          30   
2           0        98         2       123        43           9          31   
3           0        21         0       142        44          10          28   
4          -1        16        -1       134        38           9          21   
5           1        29         1       153        42           7          26   
..        ...       ...       ...       ...       ...         ...         ...   
65         -1        34         0       297        39           1          27   
66         -1        45         1       267        42           6          30   
67          1        27         1       290        36           6          21   
68          3        46         1       255        44           1          33   
69          2        61        -4       397        38           7          24   

SNO Z78285_f_at  
1             0  
2            -1  
3            -2  
4             0  
5            -2  
..          ...  
65           -1  
66           -1  
67            0  
68           -1  
69            3  

[69 rows x 7070 columns]

In [17]:
df.describe()

SNO     A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
count          69           69           69           69           69   
unique         47           33           43           51           59   
top            31           25           14           23          164   
freq            4            5            4            4            3   

SNO     AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...  \
count            69           69           69           69           69  ...   
unique           33           48           50           54           62  ...   
top               8          -19          191           54          134  ...   
freq              6            4            3            4            2  ...   

SNO     U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at  \
count          69         69         69         69         69         69   
unique         35         59         16         44         15         63   
top            27        141          0         30          2         96   
freq            6          3         16          4         13          2   

SNO     Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
count          69           69           69           69  
unique         37           23           38           17  
top            39            6           30           -2  
freq            6           10            5           16  

[4 rows x 7070 columns]

In [18]:
check_nan = df.isnull()       #checking element which have NaN value
check_nan

SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
1        False        False        False        False        False   
2        False        False        False        False        False   
3        False        False        False        False        False   
4        False        False        False        False        False   
5        False        False        False        False        False   
..         ...          ...          ...          ...          ...   
65       False        False        False        False        False   
66       False        False        False        False        False   
67       False        False        False        False        False   
68       False        False        False        False        False   
69       False        False        False        False        False   

SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...  \
1          False        False        False        False        False  ...   
2          False        False        False        False        False  ...   
3          False        False        False        False        False  ...   
4          False        False        False        False        False  ...   
5          False        False        False        False        False  ...   
..           ...          ...          ...          ...          ...  ...   
65         False        False        False        False        False  ...   
66         False        False        False        False        False  ...   
67         False        False        False        False        False  ...   
68         False        False        False        False        False  ...   
69         False        False        False        False        False  ...   

SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at  \
1        False      False      False      False      False      False   
2        False      False      False      False      False      False   
3        False      False      False      False      False      False   
4        False      False      False      False      False      False   
5        False      False      False      False      False      False   
..         ...        ...        ...        ...        ...        ...   
65       False      False      False      False      False      False   
66       False      False      False      False      False      False   
67       False      False      False      False      False      False   
68       False      False      False      False      False      False   
69       False      False      False      False      False      False   

SNO  Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
1        False        False        False        False  
2        False        False        False        False  
3        False        False        False        False  
4        False        False        False        False  
5        False        False        False        False  
..         ...          ...          ...          ...  
65       False        False        False        False  
66       False        False        False        False  
67       False        False        False        False  
68       False        False        False        False  
69       False        False        False        False  

[69 rows x 7070 columns]

In [19]:
(check_nan.sum()).sum()             #checking how many elements have NaN values 

0

In [20]:
new_df=df.clip(2,16000)             # clip between 2 and 16000
new_df

SNO A28102_at AB000114_at AB000115_at AB000220_at AB000409_at AB000449_at  \
1          30          22          29          76         167          32   
2          46          31          70         208         211          15   
3          31          19          12         244         179         229   
4          31          16          11          39         119          19   
5          26          26          14          85         161          34   
..        ...         ...         ...         ...         ...         ...   
65         68          21          35          30         131           8   
66         77          22          30          31         132           6   
67         56          25          65          31         158           6   
68         41          21          32          27         164           8   
69         38          17          25          16         172          10   

SNO AB000450_at AB000460_at AB000462_at AB000464_at  ... U48730_at U58516_at  \
1             3         165          47         101  ...        27       161   
2             2         184          36         130  ...        27       265   
3             5         219          41         131  ...        24       126   
4             5         156          26          86  ...        27       163   
5             2         206          34         140  ...        41       138   
..          ...         ...         ...         ...  ...       ...       ...   
65           22         140          37          81  ...        18       364   
66            2         150          43         128  ...        26       251   
67           27         173          54         108  ...        17       315   
68           13         165          74         121  ...        21       248   
69            4         145          48         118  ...        16       285   

SNO U73738_at X06956_at X16699_at X83863_at Z17240_at L49218_f_at M71243_f_at  \
1           2        34         2       116        44           6          30   
2           2        98         2       123        43           9          31   
3           2        21         2       142        44          10          28   
4           2        16         2       134        38           9          21   
5           2        29         2       153        42           7          26   
..        ...       ...       ...       ...       ...         ...         ...   
65          2        34         2       297        39           2          27   
66          2        45         2       267        42           6          30   
67          2        27         2       290        36           6          21   
68          3        46         2       255        44           2          33   
69          2        61         2       397        38           7          24   

SNO Z78285_f_at  
1             2  
2             2  
3             2  
4             2  
5             2  
..          ...  
65            2  
66            2  
67            2  
68            2  
69            3  

[69 rows x 7070 columns]

In [21]:
new_df.max()                  #maximum of new_df

SNO
A28102_at      112
AB000114_at     59
AB000115_at    219
AB000220_at    634
AB000409_at    308
              ... 
X83863_at      941
Z17240_at       80
L49218_f_at     17
M71243_f_at     71
Z78285_f_at     17
Length: 7070, dtype: object

In [22]:
df.max()       

SNO
A28102_at      112
AB000114_at     59
AB000115_at    219
AB000220_at    634
AB000409_at    308
              ... 
X83863_at      941
Z17240_at       80
L49218_f_at     17
M71243_f_at     71
Z78285_f_at     17
Length: 7070, dtype: object

In [23]:
df.min()

SNO
A28102_at        1
AB000114_at      3
AB000115_at     -9
AB000220_at     16
AB000409_at     39
              ... 
X83863_at       74
Z17240_at       14
L49218_f_at    -20
M71243_f_at     11
Z78285_f_at    -44
Length: 7070, dtype: object

In [24]:
new_df.min()

SNO
A28102_at       2
AB000114_at     3
AB000115_at     2
AB000220_at    16
AB000409_at    39
               ..
X83863_at      74
Z17240_at      14
L49218_f_at     2
M71243_f_at    11
Z78285_f_at     2
Length: 7070, dtype: object

In [25]:
from sklearn import preprocessing

In [26]:
class_df = pd.read_csv('pp5i_train_class.txt')           ##read train class data
class_df
class_np = class_df.to_numpy()                           #convert to numpy 

le = preprocessing.LabelEncoder()                        
le.fit(class_np)
train_class = le.transform(class_np)

C:\Users\ashhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ashhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [27]:
train_class

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1])

In [28]:
dfy=pd.DataFrame(train_class)              #convert into panda and make this to dataframe

In [29]:
dfy

0
0   2
1   2
2   2
3   2
4   2
.. ..
64  1
65  1
66  1
67  1
68  1

[69 rows x 1 columns]

In [30]:
new_df

SNO A28102_at AB000114_at AB000115_at AB000220_at AB000409_at AB000449_at  \
1          30          22          29          76         167          32   
2          46          31          70         208         211          15   
3          31          19          12         244         179         229   
4          31          16          11          39         119          19   
5          26          26          14          85         161          34   
..        ...         ...         ...         ...         ...         ...   
65         68          21          35          30         131           8   
66         77          22          30          31         132           6   
67         56          25          65          31         158           6   
68         41          21          32          27         164           8   
69         38          17          25          16         172          10   

SNO AB000450_at AB000460_at AB000462_at AB000464_at  ... U48730_at U58516_at  \
1             3         165          47         101  ...        27       161   
2             2         184          36         130  ...        27       265   
3             5         219          41         131  ...        24       126   
4             5         156          26          86  ...        27       163   
5             2         206          34         140  ...        41       138   
..          ...         ...         ...         ...  ...       ...       ...   
65           22         140          37          81  ...        18       364   
66            2         150          43         128  ...        26       251   
67           27         173          54         108  ...        17       315   
68           13         165          74         121  ...        21       248   
69            4         145          48         118  ...        16       285   

SNO U73738_at X06956_at X16699_at X83863_at Z17240_at L49218_f_at M71243_f_at  \
1           2        34         2       116        44           6          30   
2           2        98         2       123        43           9          31   
3           2        21         2       142        44          10          28   
4           2        16         2       134        38           9          21   
5           2        29         2       153        42           7          26   
..        ...       ...       ...       ...       ...         ...         ...   
65          2        34         2       297        39           2          27   
66          2        45         2       267        42           6          30   
67          2        27         2       290        36           6          21   
68          3        46         2       255        44           2          33   
69          2        61         2       397        38           7          24   

SNO Z78285_f_at  
1             2  
2             2  
3             2  
4             2  
5             2  
..          ...  
65            2  
66            2  
67            2  
68            2  
69            3  

[69 rows x 7070 columns]

In [31]:
chi2_features = SelectKBest(chi2,k=7070)             #implementation of chi square algorithm for feature selection 
X_t= chi2_features.fit_transform(new_df,dfy)

In [32]:
X_t


array([[30, 22, 29, ..., 6, 30, 2],
       [46, 31, 70, ..., 9, 31, 2],
       [31, 19, 12, ..., 10, 28, 2],
       ...,
       [56, 25, 65, ..., 6, 21, 2],
       [41, 21, 32, ..., 2, 33, 2],
       [38, 17, 25, ..., 7, 24, 3]], dtype=object)

In [33]:
X_t.shape

(69, 7070)

In [34]:
f_score=chi2(new_df,train_class)                #score calculation

In [35]:
f_score 

(array([277.08876054,  27.63992804, 854.86866117, ...,   4.01205944,
        135.74476417,   6.31755206]),
 array([9.45480335e-059, 1.47541106e-005, 9.98879534e-184, ...,
        4.04376242e-001, 2.29849779e-028, 1.76655243e-001]))

In [36]:
np.max(f_score[1])

1.0

In [37]:
pvalue=pd.Series(f_score[1])    #pvalue=score
pvalue.index=new_df.columns     
pvalue

SNO
A28102_at       9.454803e-59
AB000114_at     1.475411e-05
AB000115_at    9.988795e-184
AB000220_at    3.601935e-157
AB000409_at     4.938391e-52
                   ...      
X83863_at       0.000000e+00
Z17240_at       6.963250e-28
L49218_f_at     4.043762e-01
M71243_f_at     2.298498e-28
Z78285_f_at     1.766552e-01
Length: 7070, dtype: float64

In [38]:
pval=pd.DataFrame(pvalue)
pval

0
SNO                       
A28102_at     9.454803e-59
AB000114_at   1.475411e-05
AB000115_at  9.988795e-184
AB000220_at  3.601935e-157
AB000409_at   4.938391e-52
...                    ...
X83863_at     0.000000e+00
Z17240_at     6.963250e-28
L49218_f_at   4.043762e-01
M71243_f_at   2.298498e-28
Z78285_f_at   1.766552e-01

[7070 rows x 1 columns]

In [39]:
ndf=new_df.T[:]                   # put a rank column in new_df 
ndf['Rank'] = pvalue
ndf_sort=ndf.sort_values('Rank',ascending = True)
xx = ndf_sort.iloc[:1000,:]
xx


1    2    3    4    5    6    7    8    9   10  ...   61   62  \
SNO                                                          ...             
U67171_at  358  600  520  463  746  585  846  130  318   72  ...  514  708   
M55172_at    2    2    2    2    2    2    2    2    2    2  ...    2    2   
X58072_at    2    2    2    2    2    2    2    2    2    2  ...    2    2   
X72727_at  637  508  588  560  592  701  669   92   67   82  ...  460  413   
M54927_at    8   15   10   35    9   17    2   15   27   46  ...  214   49   
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
U33447_at    2    2    2    2    2    2    2    2    2    2  ...    6    2   
U32944_at  548  627  510  664  483  526  744  155  170  135  ...  743  813   
X81817_at  208  226  522  265  649  397  505  102  307  129  ...  415  546   
X81895_at    2    2    3    2    2    2    2    2    2    2  ...   17    2   
U32331_at   46  146   62   23   28   30   12   22   33   34  ...  375  237   

            63   64   65   66   67   68   69 Rank  
SNO                                                
U67171_at  637  709  771  749  712  743  816  0.0  
M55172_at   12   44   87   88   25   24   25  0.0  
X58072_at    2    2    2    2    2    2    2  0.0  
X72727_at  333  523  499  514  399  343  210  0.0  
M54927_at   98  581  718  919  564  384  320  0.0  
...        ...  ...  ...  ...  ...  ...  ...  ...  
U33447_at    2  121  122  262  172   74   73  0.0  
U32944_at  694  630  702  659  729  615  579  0.0  
X81817_at  532  391  394  378  402  351  349  0.0  
X81895_at    2   94   69   73   75   19   35  0.0  
U32331_at  231  202  256  257  248  223  246  0.0  

[1000 rows x 70 columns]

In [40]:
new_df1 = v_test.T[:]
new_df1['Rank'] = pvalue
q=new_df1.sort_values('Rank',ascending = True)      # make this into ascending order


In [41]:
x_train = xx.drop('Rank',axis=1)               # now drop Rank column 
x_train2 = x_train.to_numpy()
x_train2 = x_train2[:].T
x_train2

array([[358, 2, 2, ..., 208, 2, 46],
       [600, 2, 2, ..., 226, 2, 146],
       [520, 2, 2, ..., 522, 3, 62],
       ...,
       [712, 25, 2, ..., 402, 75, 248],
       [743, 24, 2, ..., 351, 19, 223],
       [816, 25, 2, ..., 349, 35, 246]], dtype=object)

In [42]:
x_train2.shape

(69, 1000)

In [43]:
q

101  102  103  104  105  106  107  108  109  110  ...  115  \
SNO                                                                 ...        
U67171_at         108  713  398  253  678  164  235  667  750  744  ...  122   
M55172_at           3    2    3    2    2    2    2    2    2   29  ...    2   
X58072_at           2    2    2    2    2    2    2    2    2    2  ...    2   
X72727_at          61  640  116  207  710   92  160  655  581  492  ...  166   
M54927_at          31    5    3   16    6  321  278   23  107  735  ...   10   
...               ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
L41680_at           2    2    2    2    2    2    2    2    2    2  ...    2   
HG3991-HT4261_at    2    2    2    2    2    2    2    2    2    2  ...    2   
X97261_r_at         2    2    2    2    2    2    2    2    2    2  ...    2   
U70663_at           2    2    2    2    2    2    2    2    2    2  ...    2   
U63312_at           2    2   27    2    2    2   11    2    2    2  ...   13   

                  116  117  118  119  120  121  122  123 Rank  
SNO                                                            
U67171_at         109  291  481  430  512  467  194  460  0.0  
M55172_at           2    2    2    2    4    4    2    2  0.0  
X58072_at           2    2    2    2   80    2    2    2  0.0  
X72727_at          60  295  528  555  490  463  459  255  0.0  
M54927_at          16  541   16    9   13    9   20   12  0.0  
...               ...  ...  ...  ...  ...  ...  ...  ...  ...  
L41680_at           2    2    2    2    2    2    2    2  1.0  
HG3991-HT4261_at    2    2    2    2    2    2    2    2  1.0  
X97261_r_at         2    2    2    2    2    2    2    2  1.0  
U70663_at           2    2    2    2    2    2    2    2  1.0  
U63312_at           2    2    2    2    2    2    2    2  1.0  

[7070 rows x 24 columns]

In [44]:
x_test = new_df1.drop('Rank',axis=1)             #same procedure for test data
x_test = x_test.to_numpy()
x_test = x_test[:].T

In [45]:
x_test

array([[58, 36, 10, ..., 5, 61, 2],
       [52, 34, 255, ..., 6, 22, 2],
       [13, 32, 2, ..., 2, 55, 2],
       ...,
       [44, 34, 16, ..., 11, 34, 2],
       [56, 45, 7, ..., 3, 55, 2],
       [119, 53, 34, ..., 2, 60, 2]], dtype=object)

In [46]:
xx=x_train2
xx

array([[358, 2, 2, ..., 208, 2, 46],
       [600, 2, 2, ..., 226, 2, 146],
       [520, 2, 2, ..., 522, 3, 62],
       ...,
       [712, 25, 2, ..., 402, 75, 248],
       [743, 24, 2, ..., 351, 19, 223],
       [816, 25, 2, ..., 349, 35, 246]], dtype=object)

In [47]:
from sklearn.model_selection import train_test_split
train, validate,y_train,y_validate= train_test_split(xx,train_class, test_size=0.2, random_state=0)

In [48]:
y_train

array([2, 4, 0, 3, 2, 2, 2, 2, 0, 2, 2, 0, 1, 2, 3, 4, 3, 0, 2, 2, 0, 2,
       2, 4, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 0, 4, 0, 3, 2, 2, 2,
       0, 2, 2, 2, 2, 4, 2, 2, 1, 4, 3])

In [49]:
from sklearn.neighbors import KNeighborsClassifier


In [108]:
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)

In [109]:
classifier.fit(train, y_train)                      #apply KNN algorithm

KNeighborsClassifier(n_neighbors=7)

In [110]:
y_pred = classifier.predict(validate)

In [111]:
y_pred

array([0, 2, 2, 1, 2, 3, 2, 0, 3, 3, 2, 2, 2, 2])

In [112]:
y_validate

array([1, 2, 0, 1, 4, 3, 2, 0, 1, 3, 2, 2, 2, 2])

In [113]:
from sklearn.metrics import accuracy_score
accuracy_score(y_validate, y_pred)                     #accuracy of KNN

0.7142857142857143

In [56]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, train, y_train,cv=12)

C:\Users\ashhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=12.
  warnings.warn(


In [57]:
scores

array([0.8 , 0.8 , 0.8 , 1.  , 0.6 , 0.8 , 0.4 , 1.  , 1.  , 0.75, 0.25,
       0.75])

In [71]:
from sklearn.ensemble import RandomForestClassifier            
clf_rc = RandomForestClassifier(max_depth=3, random_state=0)

In [72]:
clf_rc.fit(train, y_train)                                     #Apply Random Forest Algorithm

RandomForestClassifier(max_depth=3, random_state=0)

In [73]:
y_pred_rc = clf_rc.predict(validate)

In [74]:
accuracy_score(y_validate, y_pred_rc)                        #score of Random Forest Algorithm

0.9285714285714286

In [75]:
from sklearn.neural_network import MLPClassifier
clf_mlp = MLPClassifier(random_state=0, max_iter=10)

In [76]:
clf_mlp.fit(train, y_train)

C:\Users\ashhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:679: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(max_iter=10, random_state=0)

In [77]:
y_pred_mlp = clf_mlp.predict(validate)

In [78]:
accuracy_score(y_validate, y_pred_mlp)

0.7857142857142857

In [79]:
from sklearn.tree import DecisionTreeClassifier
clf_dc = DecisionTreeClassifier(random_state=0)

In [80]:
clf_dc.fit(train, y_train)

DecisionTreeClassifier(random_state=0)

In [81]:
y_pred_DC = clf_dc.predict(validate)

In [69]:
accuracy_score(y_validate, y_pred_DC)

0.7857142857142857