In [77]:
import pandas as pd
from sklearn import preprocessing
import warnings
warnings.filterwarnings('ignore')


In [78]:
df_train= pd.read_csv('pp5i_train.gr.csv')
df_train
df_test= pd.read_csv('pp5i_test.gr.csv')
df_test

SNO  101  102  103  104  105  106  107  108  109  ...  114  115  \
0       A28102_at   58   52   13   46   48   31   16   23   47  ...   11   19   
1     AB000114_at   36   34   32   30   22   57   17   19   29  ...   17   57   
2     AB000115_at   10  255    0   14   17   -6   15   17   33  ...   18   -2   
3     AB000220_at   64   19  133   62  110   77   22   33  132  ...   84   34   
4     AB000409_at   17  220  186  232  169  251  210  142  131  ...  209  166   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
7065    X83863_at  288  161  400  206  171  257  216  155  284  ...  164  494   
7066    Z17240_at   74   33   36   44   42   43   23   51   35  ...   39  104   
7067  L49218_f_at    5    6  -24   13    8    9    7    8    6  ...    4    7   
7068  M71243_f_at   61   22   55   51   16   82   48   34   24  ...   37   36   
7069  Z78285_f_at    0   -1    2    0   -2    9  -13   -2    1  ...    0    6   

      116  117  118  119  120  121  122  123  
0      18   70   50   29   47   44   56  119  
1      25   50   36   26   28   34   45   53  
2      -7  148  145   13  361   16    7   34  
3      30   69  108   75  184   57   26   83  
4     260  241  165  111  170  147  246  204  
...   ...  ...  ...  ...  ...  ...  ...  ...  
7065  197  277  147  113  136  157  176  198  
7066   40   31   44   39   55   48   62   37  
7067   17  -24   14  -13   10   11    3   -7  
7068   62   27   24   -1   41   34   55   60  
7069   -3  -46   -2  -24   -1    0   -8   -8  

[7070 rows x 24 columns]

In [79]:
v_train=df_train.transpose()
v_train.head()


0            1            2            3            4     \
SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at   
1           30           22           29           76          167   
2           46           31           70          208          211   
3           31           19           12          244          179   
4           31           16           11           39          119   

            5            6            7            8            9     ...  \
SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...   
1             32            3          165           47          101  ...   
2             15            2          184           36          130  ...   
3            229            5          219           41          131  ...   
4             19            5          156           26           86  ...   

          7060       7061       7062       7063       7064       7065  \
SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at   
1           27        161          0         34          2        116   
2           27        265          0         98          2        123   
3           24        126          0         21          0        142   
4           27        163         -1         16         -1        134   

          7066         7067         7068         7069  
SNO  Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
1           44            6           30            0  
2           43            9           31           -1  
3           44           10           28           -2  
4           38            9           21            0  

[5 rows x 7070 columns]

In [80]:
v_test=df_test.transpose()
v_test


0            1            2            3            4     \
SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at   
101         58           36           10           64           17   
102         52           34          255           19          220   
103         13           32            0          133          186   
104         46           30           14           62          232   
105         48           22           17          110          169   
106         31           57           -6           77          251   
107         16           17           15           22          210   
108         23           19           17           33          142   
109         47           29           33          132          131   
110         42           14           22           18          113   
111         46           20           41           30          170   
112         28           32           12           32          252   
113         25           19           13          465          135   
114         11           17           18           84          209   
115         19           57           -2           34          166   
116         18           25           -7           30          260   
117         70           50          148           69          241   
118         50           36          145          108          165   
119         29           26           13           75          111   
120         47           28          361          184          170   
121         44           34           16           57          147   
122         56           45            7           26          246   
123        119           53           34           83          204   

            5            6            7            8            9     ...  \
SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...   
101            8          -36          222          119          254  ...   
102           28            3          209           93          143  ...   
103           -6          -58          174           66          204  ...   
104           -1          -29          188           62          162  ...   
105           21           -2          158           42           59  ...   
106           -1          -87          210          179          339  ...   
107           19            4          174          124          183  ...   
108           27          -14          144           36          106  ...   
109           17           -5          167           44          100  ...   
110            8            0          140           36          104  ...   
111           11           21          175           41          111  ...   
112           30          -77          206           41          279  ...   
113          200           21          159           37           90  ...   
114           14          -39          244           85          212  ...   
115            0          -46          182           52          184  ...   
116            4          -31          157          185          247  ...   
117           13           26          238          136          135  ...   
118           15           18          169           35           84  ...   
119           69           -7          181           45          109  ...   
120            5           15          188           76          127  ...   
121            8            5          236           71          126  ...   
122            4          -19          240           77          206  ...   
123            3          -23          157          106          225  ...   

          7060       7061       7062       7063       7064       7065  \
SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at   
101         25        216          0         10         -2        288   
102         25        236          0         20          1        161   
103          7        138         -5     

In [81]:
v_train.columns=df_train['SNO']
v_test.columns=df_test['SNO']

In [82]:
v_train.head()

SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at   
1           30           22           29           76          167   
2           46           31           70          208          211   
3           31           19           12          244          179   
4           31           16           11           39          119   

SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...  \
SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...   
1             32            3          165           47          101  ...   
2             15            2          184           36          130  ...   
3            229            5          219           41          131  ...   
4             19            5          156           26           86  ...   

SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at  \
SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at   
1           27        161          0         34          2        116   
2           27        265          0         98          2        123   
3           24        126          0         21          0        142   
4           27        163         -1         16         -1        134   

SNO  Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
SNO  Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
1           44            6           30            0  
2           43            9           31           -1  
3           44           10           28           -2  
4           38            9           21            0  

[5 rows x 7070 columns]

In [83]:
v_test.head()

SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
SNO  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at   
101         58           36           10           64           17   
102         52           34          255           19          220   
103         13           32            0          133          186   
104         46           30           14           62          232   

SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...  \
SNO  AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...   
101            8          -36          222          119          254  ...   
102           28            3          209           93          143  ...   
103           -6          -58          174           66          204  ...   
104           -1          -29          188           62          162  ...   

SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at  \
SNO  U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at   
101         25        216          0         10         -2        288   
102         25        236          0         20          1        161   
103          7        138         -5         33        -21        400   
104          8        152         -2          7          2        206   

SNO  Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
SNO  Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
101         74            5           61            0  
102         33            6           22           -1  
103         36          -24           55            2  
104         44           13           51            0  

[5 rows x 7070 columns]

In [84]:
v_train=v_train.drop('SNO')

In [85]:
v_test=v_test.drop('SNO')

In [86]:
v_train.describe()

SNO     A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
count          69           69           69           69           69   
unique         47           33           43           51           59   
top            31           25           14           23          164   
freq            4            5            4            4            3   

SNO     AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...  \
count            69           69           69           69           69  ...   
unique           33           48           50           54           62  ...   
top               8          -19          191           54          134  ...   
freq              6            4            3            4            2  ...   

SNO     U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at  \
count          69         69         69         69         69         69   
unique         35         59         16         44         15         63   
top            27        141          0         30          2         96   
freq            6          3         16          4         13          2   

SNO     Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
count          69           69           69           69  
unique         37           23           38           17  
top            39            6           30           -2  
freq            6           10            5           16  

[4 rows x 7070 columns]

In [87]:
v_test.describe()

SNO     A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
count          23           23           23           23           23   
unique         21           17           21           22           22   
top            46           36           13           30          170   
freq            2            2            2            2            2   

SNO     AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  ...  \
count            23           23           23           23           23  ...   
unique           19           22           20           21           23  ...   
top               8           21          174           36          254  ...   
freq              3            2            2            2            1  ...   

SNO     U48730_at  U58516_at  U73738_at  X06956_at  X16699_at  X83863_at  \
count          23         23         23         23         23         23   
unique         15         21          9         22         14         23   
top            25        138          0         14          1        288   
freq            4          2          9          2          4          1   

SNO     Z17240_at  L49218_f_at  M71243_f_at  Z78285_f_at  
count          23           23           23           23  
unique         18           15           19           12  
top            32            6           23           -2  
freq            2            3            2            5  

[4 rows x 7070 columns]

In [88]:
v_test

SNO A28102_at AB000114_at AB000115_at AB000220_at AB000409_at AB000449_at  \
101        58          36          10          64          17           8   
102        52          34         255          19         220          28   
103        13          32           0         133         186          -6   
104        46          30          14          62         232          -1   
105        48          22          17         110         169          21   
106        31          57          -6          77         251          -1   
107        16          17          15          22         210          19   
108        23          19          17          33         142          27   
109        47          29          33         132         131          17   
110        42          14          22          18         113           8   
111        46          20          41          30         170          11   
112        28          32          12          32         252          30   
113        25          19          13         465         135         200   
114        11          17          18          84         209          14   
115        19          57          -2          34         166           0   
116        18          25          -7          30         260           4   
117        70          50         148          69         241          13   
118        50          36         145         108         165          15   
119        29          26          13          75         111          69   
120        47          28         361         184         170           5   
121        44          34          16          57         147           8   
122        56          45           7          26         246           4   
123       119          53          34          83         204           3   

SNO AB000450_at AB000460_at AB000462_at AB000464_at  ... U48730_at U58516_at  \
101         -36         222         119         254  ...        25       216   
102           3         209          93         143  ...        25       236   
103         -58         174          66         204  ...         7       138   
104         -29         188          62         162  ...         8       152   
105          -2         158          42          59  ...        27       146   
106         -87         210         179         339  ...         5       102   
107           4         174         124         183  ...        12       138   
108         -14         144          36         106  ...        47        98   
109          -5         167          44         100  ...        24       165   
110           0         140          36         104  ...        25       310   
111          21         175          41         111  ...        31       301   
112         -77         206          41         279  ...        28        69   
113          21         159          37          90  ...        19       124   
114         -39         244          85         212  ...        10        80   
115         -46         182          52         184  ...        12        74   
116         -31         157         185         247  ...         5        95   
117          26         238         136         135  ...        26       326   
118          18         169          35          84  ...        28       143   
119          -7         181          45         109  ...        25       225   
120          15         188          76         127  ...        28       197   
121           5         236          71         126  ...        20       201   
122         -19         240          77         206  ...        15       135   
123         -23         157         106         225  ...        10       236   

SNO U73738_at X06956_at X16699_at X83863_at Z17240_at L49218_f_at M71243_f_at  \
101         0        10        -2       288        74           5          61   
102         0        20         1       161        33           6   

In [89]:
df_class= pd.read_csv('pp5i_train_class.txt')

df_class

Class
0    MED
1    MED
2    MED
3    MED
4    MED
..   ...
64   JPA
65   JPA
66   JPA
67   JPA
68   JPA

[69 rows x 1 columns]

In [90]:
class_np= df_class.to_numpy()

In [91]:
L=preprocessing.LabelEncoder()
L.fit(class_np)

LabelEncoder()

In [92]:
train_class=L.transform(class_np)
train_class

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1])

In [93]:
L.classes_

array(['EPD', 'JPA', 'MED', 'MGL', 'RHB'], dtype=object)

In [94]:
v_test = v_test.clip(2,16000)
v_train = v_train.clip(2,16000)

In [95]:
from sklearn.feature_selection import mutual_info_classif
import matplotlib.pyplot as plt

In [96]:
importances = mutual_info_classif(v_train, train_class)

In [97]:
importances

array([0.20853554, 0.20873042, 0.16995482, ..., 0.09301815, 0.16407965,
       1.06669161])

In [98]:
feat_importances = pd.Series(importances, v_train.columns[0:len(v_train.columns)])
feat_importances

SNO
A28102_at      0.208536
AB000114_at    0.208730
AB000115_at    0.169955
AB000220_at    0.263495
AB000409_at    0.106561
                 ...   
X83863_at      0.338925
Z17240_at      0.324490
L49218_f_at    0.093018
M71243_f_at    0.164080
Z78285_f_at    1.066692
Length: 7070, dtype: float64

In [104]:
imp_gene_df= pd.DataFrame(feat_importances)

In [105]:
imp_gene_df.sort_values(0,ascending=False).head(10)

0
SNO                       
AF000234_at       1.320757
L20433_at         1.250097
M76732_s_at       1.244763
S60415_at         1.232562
D78333_at         1.226382
Y10508_s_at       1.223838
X83703_at         1.210814
L11329_at         1.205525
HG2797-HT2905_at  1.203116
X99947_at         1.201665

In [106]:
new_df = v_train.T[:]
new_df['Rank'] = feat_importances
new_df = new_df.sort_values('Rank',ascending = False)

In [107]:
new_df1 = v_test.T[:]
new_df1['Rank'] = feat_importances
new_df1= new_df1.sort_values('Rank',ascending = False)

In [108]:
new_df

1    2    3    4   5   6    7   8    9  10  ...  61   62  63  \
SNO                                                          ...                
AF000234_at      2    2    2    2   2   2    2   2    2   2  ...   2    2   2   
L20433_at        2    2    2    2   2   2    2   2    2   2  ...   2    2   2   
M76732_s_at      2    2    2    2   2   2    2   2   16   2  ...   2  309  56   
S60415_at        2    2    2    2   9   2   45   2    2   2  ...   2    2   2   
D78333_at        4    2    3    2  11  13    2   2    2   2  ...   4   16   4   
...             ..  ...  ...  ...  ..  ..  ...  ..  ...  ..  ...  ..  ...  ..   
J04111_at       64  158  112  111  82  30  236  23  101  60  ...  82  216  72   
M14159_cds2_at  48   85  108   27  54  46   24   8    5   2  ...  82   78  35   
U73799_at       61    2    2   94  88  46    2   2    5   2  ...  32  166  56   
M64174_at       45  111   76   58  53  89   77  52   77  30  ...  67   56  72   
X89067_at       16    3   14   15  14   6   11  36    7  26  ...  12   17  10   

                 64  65   66   67  68   69      Rank  
SNO                                                   
AF000234_at       2   2    2    2   2    2  1.320757  
L20433_at         2   2    2    2   2    2  1.250097  
M76732_s_at       2   2    2    2   2    2  1.244763  
S60415_at         2   2    2    2   2    2  1.232562  
D78333_at         2   2    2    2   2    2  1.226382  
...             ...  ..  ...  ...  ..  ...       ...  
J04111_at       172  76  101  104  72  106  0.000000  
M14159_cds2_at   63  56    2   62  48   38  0.000000  
U73799_at        45  87  117   11  19  233  0.000000  
M64174_at        73  64   63   94  77   70  0.000000  
X89067_at         5  11   13    7  11   16  0.000000  

[7070 rows x 70 columns]

In [109]:
new_df1

101 102  103 104  105 106 107 108  109  110  ...  115 116  117  \
SNO                                                         ...                 
AF000234_at      2   2    2   2    2   2   2   2    2    2  ...    2   2    2   
L20433_at        2   2    2   2    2   2   2   2    2    2  ...    2   2    2   
M76732_s_at      2   2    2   2  631   2   2   2  546    2  ...    2   2    2   
S60415_at        2   2    2   2    2   2   2   2    2    2  ...  443   2   10   
D78333_at        2   3    2   2   17   2   2   7    7    2  ...    2   2    2   
...             ..  ..  ...  ..  ...  ..  ..  ..  ...  ...  ...  ...  ..  ...   
J04111_at       52  79  151  59   45  47  62  39  198  101  ...   58  38   51   
M14159_cds2_at  60  55   69  30    3   2   2  74    2   43  ...    2   2   17   
U73799_at       23  32    2   2  117   2   5  55  162  123  ...    2   2    2   
M64174_at       90  78   30  52   61  53  69  83   49   67  ...   69  34  101   
X89067_at       21  13    2  20   19  20  20  11   13   14  ...    2   2   14   

                118 119 120  121 122  123      Rank  
SNO                                                  
AF000234_at       2   2   2    2   2    2  1.320757  
L20433_at         2   2   2    2   2    2  1.250097  
M76732_s_at       2   2   2    2   2    2  1.244763  
S60415_at         2   2   2    2   2    2  1.232562  
D78333_at         2   2   2    2   2    2  1.226382  
...             ...  ..  ..  ...  ..  ...       ...  
J04111_at       137  11  53  118  70   60  0.000000  
M14159_cds2_at  126  51   5  139   2   40  0.000000  
U73799_at        15  41  78   41  33  120  0.000000  
M64174_at        78  21  84  140  79   64  0.000000  
X89067_at        11  12  11   12  15    7  0.000000  

[7070 rows x 24 columns]

In [110]:
import numpy as np

In [121]:
x_train = new_df.drop('Rank',axis=1)
xx = x_train.iloc[:970,:]
x_train = xx.to_numpy()
x_train = x_train[:].T

In [122]:
x_train

array([[2, 2, 2, ..., 2, 47, 64],
       [2, 2, 2, ..., 2, 60, 96],
       [2, 2, 2, ..., 2, 66, 60],
       ...,
       [2, 2, 2, ..., 6, 38, 20],
       [2, 2, 2, ..., 2, 36, 11],
       [2, 2, 2, ..., 2, 33, 2]], dtype=object)

In [123]:
x_test = new_df1.drop('Rank',axis=1)
xx1 = x_test.iloc[:970,:]
x_test = xx1.to_numpy()
x_test = x_test[:].T

In [124]:
x_test

array([[2, 2, 2, ..., 2, 47, 2],
       [2, 2, 2, ..., 2, 51, 132],
       [2, 2, 2, ..., 14, 56, 78],
       ...,
       [2, 2, 2, ..., 2, 26, 72],
       [2, 2, 2, ..., 2, 65, 3],
       [2, 2, 2, ..., 2, 23, 67]], dtype=object)

In [125]:
train_class

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1])

In [126]:
xx = xx.T[:]

In [127]:
from sklearn.model_selection import train_test_split
train, validate,y_train,y_validate= train_test_split(xx,train_class, test_size=0.2)

In [128]:
y_train

array([2, 3, 2, 2, 0, 2, 1, 2, 2, 0, 2, 2, 4, 2, 2, 0, 2, 2, 2, 2, 3, 4,
       4, 2, 0, 0, 3, 2, 2, 1, 2, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 2, 4, 2,
       2, 2, 2, 2, 2, 3, 2, 3, 1, 2, 2])

## Applying Classifiers
-KNN
-Naive Bayes
-Decision Tree 
-Random Forest
-MLP

In [129]:
from sklearn.neighbors import KNeighborsClassifier


In [130]:
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier.fit(train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [131]:
y_pred = classifier.predict(validate)
y_pred

array([2, 4, 2, 2, 0, 0, 3, 0, 1, 2, 0, 2, 2, 3])

In [132]:
y_pred_test = classifier.predict(x_test)
print(y_pred_test)
L.classes_

[2 0 2 2 0 2 2 2 0 1 1 2 2 2 2 2 3 2 2 4 0 2 2]


array(['EPD', 'JPA', 'MED', 'MGL', 'RHB'], dtype=object)

In [133]:
y_validate

array([2, 4, 2, 2, 4, 4, 3, 0, 1, 2, 0, 2, 2, 3])

In [134]:
from sklearn.metrics import accuracy_score
accuracy_score(y_validate, y_pred)

0.8571428571428571

In [135]:
KNN=accuracy_score(y_validate, y_pred)

In [136]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, train, y_train,cv=10)

In [137]:
scores

array([0.83333333, 0.83333333, 0.83333333, 0.66666667, 0.66666667,
       0.8       , 0.8       , 0.8       , 1.        , 0.8       ])

In [138]:
train_class

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1])

In [139]:
from sklearn.naive_bayes import GaussianNB

In [140]:
clf = GaussianNB()
clf.fit(train, y_train)

GaussianNB()

In [141]:
y_pred_NB = clf.predict(validate)

In [142]:
y_pred_NB

array([2, 0, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 2, 3])

In [143]:
accuracy_score(y_validate, y_pred_NB)

0.6428571428571429

In [144]:
NB=accuracy_score(y_validate, y_pred_NB)

In [145]:
from sklearn.tree import DecisionTreeClassifier
clf_dc = DecisionTreeClassifier(random_state=0)

In [146]:
clf_dc.fit(train, y_train)

DecisionTreeClassifier(random_state=0)

In [147]:
y_pred_DC = clf_dc.predict(validate)

In [148]:
accuracy_score(y_validate, y_pred_DC)

0.7857142857142857

In [149]:
DT=accuracy_score(y_validate, y_pred_DC)

In [150]:
from sklearn.ensemble import RandomForestClassifier
clf_rc = RandomForestClassifier(max_depth=2, random_state=0)

In [151]:
clf_rc.fit(train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [152]:
y_pred_rc = clf_rc.predict(validate)

In [153]:
accuracy_score(y_validate, y_pred_rc)

0.7857142857142857

In [154]:
RF=accuracy_score(y_validate, y_pred_rc)

In [155]:
from sklearn.neural_network import MLPClassifier
clf_mlp = MLPClassifier(random_state=0, max_iter=9)

In [156]:
clf_mlp.fit(train, y_train)

MLPClassifier(max_iter=9, random_state=0)

In [157]:
y_pred_mlp = clf_mlp.predict(validate)

In [158]:
accuracy_score(y_validate, y_pred_mlp)

0.9285714285714286